config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  # For test for Gmap
#  resources :gmap
  
  # ROOT
  root "welcome#index"

  # Home page
  get "welcome", to: "welcome#index"

  get "welcome/sitemap"
  get "welcome/about"
  get "welcome/contact_us"
  get "welcome/terms_of_service"
  get "welcome/privacy_policy"
  get "welcome/faq"

  # Pages
  get "borrow_from_others", to: "user_profiles#borrow_from_others"

  # Resources
  resources :items
  resources :user_profiles, :path => "account/profiles"
  resources :categories

  get "lend_to_others", to: "user_profiles#lend_to_others"
  get "lend_rating", to: "user_profiles#lend_rating"
  get "borrow_rating", to: "user_profiles#borrow_rating"
  get "comment_history", to: "user_profiles#comment_history"
  resources :user_profiles do
    resources :items
  end

  resources :items do
    collection { post :search, to: "items#index" }
  end

  #resources :borrow_requests

  resources :items do
    resources :borrow_requests
  end
  
  resources :items do
    resources :comments
  end

  #  devise_for :users, skip: [:sessions]
  #  devise_scope :user do
  #    get 'signin', to: 'devise/sessions#new', as: :new_user_session
  #    post 'signin', to: 'devise/sessions#create', as: :user_session
  #    delete 'signout', to: 'devise/sessions#destroy', as: :destroy_user_session
  #  end

  devise_for :users,
    :path => "account",
    :path_names => {
      :sign_in => "login",
      :sign_out => "logout",
      :password => "secret",
      :confirmation => "verification",
      :unlock => "unblock",
    }, skip: [:registration]
  devise_scope :user do
    get "/account/cancel", to: "devise/registrations#cancel", as: :cancel_user_registration
    get "/account/sign_up", to: "devise/registrations#new", as: :new_user_registration
    get "/account/edit", to: "devise/registrations#edit", as: :edit_user_registration
    post "/account", to: "devise/registrations#create", as: :user_registration
  end
end

app/models/user_profile.rb
class UserProfile < ApplicationRecord
  belongs_to :user, optional: true
  has_many :items, dependent: :destroy
  has_many :borrow_requests, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_one_attached :avatar

  # validate avatar
  validate :correct_avatar_type

  # validate postal code must exist
  validates :username, presence: {message: "must exist"}
  validate :address_exists?
  validate :lrating?
  validate :brating?
  geocoded_by :address
  after_validation :geocode

  before_create :set_default_avatar
  after_save :update_profile_id_in_users

  def update_profile_id_in_users
    @user = User.find(self.user_id)
    if @user.present?
      @user.update_attribute(:user_profile_id, self.id)
    end
  end

  def lrating?
    if self[:lend_rating]==nil
      return
    end

    if self[:lend_rating] > 5
      self.errors.add(:lend_rating,"can not be greater than 5")
    end
    if self[:lend_rating] < 0
      self.errors.add(:lend_rating,"can not be smaller than 0")
    end
  end

  def brating?
    if self[:borrow_rating]==nil
      return
    end

    if self[:borrow_rating] > 5
      self.errors.add(:lend_rating,"can not be greater than 5")
    end
    if self[:borrow_rating] < 0
      self.errors.add(:lend_rating,"can not be smaller than 0")
    end
  end

  def address_exists?
    if self.address.nil?
      return
    end

    if self.address["street_address"] == ""
      self.errors.add(:street_address, "can not be empty")
    end

    if self.address["city"] == ""
      self.errors.add(:city, "can not be empty")
    end

    if (self.address["postal_code"] =~ /\A[abceghjklmnprstvxyABCEGHJKLMNPRSTVXY]{1}\d{1}[a-zA-Z]{1}[ -]?\d{1}[a-zA-Z]{1}\d{1}\z/).nil?
      self.errors.add(:postal_code, "invalid!")
    end
  end

  def correct_avatar_type
      if self.avatar.attached? && !self.avatar.content_type.start_with?('image/');
        self.errors.add(:self, 'Must be an image')
      end
    end

  def set_default_avatar
    if !self.avatar.attached?
      self.avatar.attach(io: File.open(Rails.root.join("app", "assets", "images", "default_avatar.png")), filename: "default_avatar.png", content_type: "image/png")
    end
  end
end

app/controllers/user_profiles_controller.rb
class UserProfilesController < ApplicationController
  def index
    @user_profiles = UserProfile.all
  end

  def show
    @user_profile = UserProfile.find(params[:id])
  end

  def new
    @user_profile = UserProfile.new
  end

  def edit
    @user_profile = UserProfile.find(params[:id])
  end

  def create
    lend_rating = 1
    @user_profile = UserProfile.new(profile_params)
    #    @user_profile.auto_fill_username_and_account(current_user)

    if @user_profile.save
      flash[:notice] = "Profile added"
      redirect_to :root
    else
      @s = ""
      for m in @user_profile.errors.full_messages
        @s = @s + m + ".   "
      end
      flash[:alert] = @s

      render "new"
    end
  end

  def update
    @id = params[:id]

    if (@id.to_i == current_user.id)
      @user_profile = UserProfile.find(params[:id])
      @registerInProgress = @user_profile.birthday.nil?
      @updateResult = @user_profile.update(profile_params)

      if @updateResult && !@registerInProgress
        @user_profile.errors.clear
        flash[:notice] = "Profile updated"
        redirect_to @user_profile
      elsif @updateResult && @registerInProgress
        @user_profile.errors.clear
        flash[:notice] = "Profile added"
        redirect_to :root
      else
        flash[:alert] = @user_profile.errors.full_messages.map(&:inspect).join()
        render "edit"
      end
    else
      @lrating = params.require(:user_profile)
      @lrating = @lrating[:lend_rating].to_i
      if (@lrating!=0)
        puts "22222222"
        @user_profile = UserProfile.find(params[:id])
        @l_rating = @user_profile.lend_rating
        @l_people = @user_profile.lpeople
        @l_rating = @l_rating * @l_people
        @l_people = @l_people + 1
        @rating = params.require(:user_profile)
        @rating = @rating[:lend_rating].to_i
        @l_rating = (@l_rating + @rating) / @l_people
        if @user_profile.update_attribute(:lend_rating, @l_rating) && @user_profile.update_attribute(:lpeople, @l_people)
          redirect_to :root
        else
          render "lend_rating"
        end
      else
        puts "333333333"
        @user_profile = UserProfile.find(params[:id])
        @b_rating = @user_profile.borrow_rating
        @b_people = @user_profile.bpeople
        @b_rating = @b_rating * @b_people
        @b_people = @b_people + 1
        @rating = params.require(:user_profile)
        @rating = @rating[:borrow_rating].to_i
        @b_rating = (@b_rating + @rating) / @b_people
        if @user_profile.update_attribute(:borrow_rating, @b_rating) && @user_profile.update_attribute(:bpeople, @b_people)
          redirect_to :root
        else
          render "borrow_rating"
        end
      end
    end
  end

  #items that I lent to others
  def lend_to_others
    @user_profile = UserProfile.find(current_user.id)
    @items = @user_profile.items
  end

  #items that I borrowed from others
  def borrow_from_others
    @user_profile = UserProfile.find(current_user.id)
    @user_name = @user_profile.username
    @borrow_requests = @user_profile.borrow_requests
  end

  def comment_history
    @user_profile = UserProfile.find(current_user.id)

  end

  #rating other people
  def lend_rating
    @user_profile = UserProfile.find(params[:id])
  end

  def borrow_rating
    @user_profile = UserProfile.find(params[:id])
  end
  private

  def profile_params
    params.require(:user_profile).permit(:account_id, :username, :first_name, :last_name, :birthday, :avatar, address: [:street_address, :city, :province_id, :postal_code])
  end

  def rate_params
    params.require(:user_profile).permit(:lend_rating, :lpeople)
  end
end

app/helpers/user_profiles_helper.rb
module UserProfilesHelper
  def getProvinceName(id)
    @province = Province.find(id)
    @province.province
  end
end

app/views/user_profiles/_brating_form.html.erb
<div class = "profile_form" >

  <%= form_with model: @user_profile, local: true do |form| %>

    <div class="field form-group">
      <%= form.label :borrow_rating, "Rate your borrow experience (1-5)" %><br>
      <%= form.number_field :borrow_rating, min:1, max:5, default:5, :class => 'form-control'%>
    </div>

    <div class="actions">
      <p>
        <%= form.submit "Complete rating", :class => 'form-control'%>
      </p>
    </div>

  <% end %>
</div>

app/views/user_profiles/_rating_form.html.erb
<div class = "profile_form" >

  <%= form_with model: @user_profile, local: true do |form| %>

    <div class="field">
      <%= form.label :lend_rating, "Rate your lend experience (1-5)" %><br>
      <%= form.number_field :lend_rating, min:0, max:5, default:5, :class => 'form-control'%>
    </div>



    <div class="actions">
      <p>
        <%= form.submit "Complete rating", :class => 'form-control'%>
      </p>
    </div>

  <% end %>
</div>

app/views/user_profiles/borrow_from_others.erb
<head>
  <link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
  <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>
  <script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
</head>

<div class="list-container">
  <row>
    <h1 class="list-header">Borrow requests</h1>
  </row>
  <row>
    <div class="container">
      <div class="panel-group" id="accordion">
        <div class="panel panel-default">
          <div class="panel-heading">
            <h4 class="panel-title">
              <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion" href="#collapseOne">Pending</a>
            </h4>
          </div>
          <div id="collapseOne" class="panel-collapse collapse in">
            <div class="panel-body">
            <div style="overflow-x:auto;">
              <% @borrow_requests.each do |borrow_request| %>
                <table>
                  <% if borrow_request.approval.nil?%>
                  <tr>
                  <td>
                    <%= borrow_request.item.item_name %>
                  </td>
                  <td>
                    <%= getCategoryName(borrow_request.item.category_id) %>
                  </td>
                  <td>
                    Lender: 
                    <%= borrow_request.item.user_profile.username %>
                  </td>
                  <td>
                    <%= borrow_request.borrow_date%> to <%=borrow_request.return_date%>
                  </td>
                  <td>
                    <%= link_to 'Show Request', item_borrow_request_path(:item_id=>borrow_request.item.id, :id=>borrow_request.id) %>
                  </td>
                  <td>
                    <%= link_to 'Show Item', user_profile_item_path(:user_profile_id=>current_user.id, :id=>borrow_request.item.id) %>
                  </td>
                  <td>
                    <%= link_to 'Cancel Request', item_borrow_request_path(:item_id=>borrow_request.item.id, :id=>borrow_request.id),
                                  method: :delete,
                                  data: { confirm: 'Are you sure to cancel the request?'} %>
                  </td>
                  </tr>
                  <% end %>
                </table>
                
              <% end %>
              </div>
            </div>
          </div>
        </div>
        <div class="panel panel-default">
          <div class="panel-heading">
            <h4 class="panel-title">
              <a class="accordion-toggle collapsed" data-toggle="collapse" data-parent="#accordion" href="#collapse2">Accpeted</a>
            </h4>
          </div>
          <div id="collapse2" class="panel-collapse collapse">
            <div class="panel-body">
            <div style="overflow-x:auto;">
              <% @borrow_requests.each do |borrow_request| %>
              <table>
                <% if borrow_request.approval == true && borrow_request.return_status != 2 %>
                <tr>
                  <td>
                    <%= borrow_request.item.item_name %>
                  </td>
                  <td>
                    <%= getCategoryName(borrow_request.item.category_id) %>
                  </td>
                  <td>
                    Lender: 
                    <%= borrow_request.item.user_profile.username %>
                  </td>
                  <td>
                    <%= borrow_request.borrow_date%> to <%=borrow_request.return_date%>
                  </td>
                  <td>
                    <%= link_to 'Show Request', item_borrow_request_path(:item_id=>borrow_request.item.id, :id=>borrow_request.id) %> |</td>
                  <td>
                    <%= link_to 'Show Item', user_profile_item_path(:user_profile_id=>current_user.id, :id=>borrow_request.item.id) %> | </td>

                  <td>
                    <%= link_to 'Remove', item_borrow_request_path(:item_id=>borrow_request.item.id, :id=>borrow_request.id),
                                  method: :delete,
                                  data: { confirm: 'Are you sure to cancel the request?'} %>
                  </td>
                </tr>
                <% end %>
              </table>
              
              <% end %>
              </div>
            </div>
          </div>
        </div>
        <div class="panel panel-default">
          <div class="panel-heading">
            <h4 class="panel-title">
              <a class="accordion-toggle collapsed" data-toggle="collapse" data-parent="#accordion" href="#collapse3">Rejected</a>
            </h4>
          </div>
          <div id="collapse3" class="panel-collapse collapse">
            <div class="panel-body">
            <div style="overflow-x:auto;">
              <% @borrow_requests.each do |borrow_request| %>
              <table>
                <% if borrow_request.approval == false%>
                <tr>
                  <td>
                    <%= borrow_request.item.item_name %>
                  </td>
                  <td>
                    <%= getCategoryName(borrow_request.item.category_id) %>
                  </td>
                  <td>
                    Lender: 
                    <%= borrow_request.item.user_profile.username %>
                  </td>
                  <td>
                    <%= borrow_request.borrow_date%> to <%=borrow_request.return_date%>
                  </td>                 
                  <td>
                    <%= link_to 'Show Request', item_borrow_request_path(:item_id=>borrow_request.item.id, :id=>borrow_request.id) %> |</td>
                  <td>
                    <%= link_to 'Show Item', user_profile_item_path(:user_profile_id=>current_user.id, :id=>borrow_request.item.id) %> | </td>
                  <td>
                    <%= link_to 'Remove', item_borrow_request_path(:item_id=>borrow_request.item.id, :id=>borrow_request.id),
                                  method: :delete,
                                  data: { confirm: 'Are you sure to cancel the request?'} %>
                  </td>
                </tr>
                <% end %>
              </table>              
              <% end %>
              </div>
            </div>
          </div>
        </div>
        <div class="panel panel-default">
          <div class="panel-heading">
            <h4 class="panel-title">
              <a class="accordion-toggle collapsed" data-toggle="collapse" data-parent="#accordion" href="#collapse4">History</a>
            </h4>
          </div>
          <div id="collapse4" class="panel-collapse collapse">
            <div class="panel-body">
            <div style="overflow-x:auto;">
              <% @borrow_requests.each do |borrow_request| %>
              <table style= "width:100%">
                <% if borrow_request.return_status == 2%>
                <tr>
                  <td>
                    <%= borrow_request.item.item_name %>
                  </td>
                  <td>
                    <%= getCategoryName(borrow_request.item.category_id) %>
                  </td>
                  <td>
                    Lender: 
                    <%= borrow_request.item.user_profile.username %>
                  </td>
                  <td>
                    <%= borrow_request.actual_borrow_date%> to <%=borrow_request.actual_return_date%>
                  </td>
                  <td>
                    <%= link_to 'Show Request', item_borrow_request_path(:item_id=>borrow_request.item.id, :id=>borrow_request.id) %> |</td>
                  <td>
                    <%= link_to 'Show Item', user_profile_item_path(:user_profile_id=>current_user.id, :id=>borrow_request.item.id) %> | </td>
                  <td>
                    <%= link_to 'Remove', item_borrow_request_path(:item_id=>borrow_request.item.id, :id=>borrow_request.id),
                                  method: :delete,
                                  data: { confirm: 'Are you sure to cancel the request?'} %>
                  </td>
                </tr>
                <% end %>
              </table>
              <% end %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </row>
</div>

app/views/user_profiles/borrow_rating.html.erb
<div class='row'>
  <div class='col-2'>
  </div>
  <div class="col-8">
    <div class="text-form form-group">
      <h1>Review</h1>
      <%= render 'brating_form' %>
    </div>
  </div>
</div>

app/views/user_profiles/comment_history.html.erb
<head>
  <link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
  <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>
  <script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
</head>


<div class="list-container">
  <row>
    <h1 class="list-header">Comment History</h1>
  </row>
  <row>
    <div class="container">
      <div class="panel-group" id="accordion">
        <div class="panel panel-default">
          <div class="panel-heading">
            <h4 class="panel-title">
              <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion" href="#collapseOne">Pending</a>
            </h4>
          </div>
          <div id="collapseOne" class="panel-collapse collapse in">
            <div class="panel-body">
            <div style="overflow-x:auto;">
            <table>

            <% @user_profile.comments.each do |current_req|%>
            <tr>
              <td><%=link_to current_req.item.item_name, item_path(current_req.item_id)%></td>
              <td><%= current_req.comment_message %>
                | <%= current_req.comment_date %></td>
              <td> <%=link_to "Edit", edit_item_comment_path(current_req.item_id,current_req.id),
              data: { confirm: 'Are you sure?'}, class: "btn btn-info" %></td>
              <td> <%=link_to "Delete", item_comment_path(current_req.item_id,current_req.id),
                       method: :delete,
                       data: { confirm: 'Are you sure?'}, class: "btn btn-info" %></td>
    
            </tr>
            <% end %>
    
        </table> 
              </div>
            </div>
          </div>
        </div>
        </div>
        </div>
      </row>
    </div>

app/views/user_profiles/edit.html.erb
<%= render 'change_profile' %>

app/views/user_profiles/index.html.erb
<h1>Listing user info (internal test)</h1>
<table>
  <tr>
    <th>profile_id</th>
    <th>user_id</th>
    <th>username</th>
    <th>first_name</th>
    <th>last_name</th>
    <th>birthday</th>
    <th>street_address</th>
    <th>city</th>
    <th>province</th>
    <th>postal_code</th>
    <th>latitude</th>
    <th>longitude</th>
    <th></th>
  </tr>
 
  <% @user_profiles.each do |user_profile| %>
    <tr>
      <td><%= user_profile.id %></td>
      <td><%= user_profile.user_id %></td>
      <td><%= user_profile.username %></td>
      <td><%= user_profile.first_name %></td>
      <td><%= user_profile.last_name %></td>
      <td><%= user_profile.birthday %></td>
      <%if !user_profile.address.nil?%>
        <td><%= user_profile.address['street_address'] %></td>
        <td><%= user_profile.address['city'] %></td>
        <td><%= user_profile.address['province_id'] %></td>
        <td><%= user_profile.address['postal_code'] %></td>
      <%end%>
      <td><%= user_profile.latitude %></td>
      <td><%= user_profile.longitude %></td>
      <td><!--%= user_account.salt %--></td>
      <td><!--%= link_to 'Show', user_profile_path(user_profile) %--></td>
      <td><!--%= link_to 'Edit', edit_user_profile_path(user_profile) %--></td>
    </tr>
  <% end %>
  <br>
  <br>
  <% @users = User.all %>
  <% @users.each do |user| %>
    <%= user.email %><br/>
    <%= user.user_profile_id %><br/>
    <%= user.encrypted_password %><br/>
  <% end %>
    
</table>

app/views/user_profiles/lend_rating.erb
<div class='row'>
  <div class='col-2'>
  </div>
  <div class="col-8">
    <div class="text-form form-group">
      <h1>Review</h1>
      <%= render 'rating_form' %>
    </div>
  </div>
</div>

app/views/user_profiles/lend_to_others.html.erb
<head>
  <link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
  <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>
  <script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
</head>

<div class="list-container">
  <row>
    <h1 class="list-header">Incoming Borrow Requests</h1>
  </row>
  <row>
    <div class="container">
      <div class="panel-group" id="accordion">
        <div class="panel panel-default">
          <div class="panel-heading">
            <h4 class="panel-title">
              <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion" href="#collapseOne">Not Read</a>
            </h4>
          </div>
          <div id="collapseOne" class="panel-collapse collapse in">
            <div class="panel-body">
            <div style="overflow-x:auto;">
              <% @items.each do |item| %>
              <% if !(item.borrow_requests.nil?) %>
              <% item.borrow_requests.each do |borrow_request| %>
              <tr>
                <table>
                  <% if borrow_request.read_status==false %>
                  <td>
                    <%= borrow_request.item.item_name %>
                  </td>
                  <td>
                    <%= getCategoryName(borrow_request.item.category_id) %>
                  </td>
                  <td>
                    Borrower: 
                    <%= link_to borrow_request.user_profile.username, user_profile_path(borrow_request.user_profile.id)%>
                  </td>
                  <td>
                    <%= borrow_request.borrow_date%> to <%=borrow_request.return_date%>
                  </td>                  
                  <td>
                    <%= link_to 'Show Request', item_borrow_request_path(:item_id=>borrow_request.item.id, :id=>borrow_request.id) %>
                  </td>
                  <td>
                    <%= link_to 'Show Item', user_profile_item_path(:user_profile_id=>current_user.id, :id=>borrow_request.item.id) %>
                  </td>
                  <td>
                    <%= link_to 'Remove', item_borrow_request_path(:item_id=>borrow_request.item.id, :id=>borrow_request.id),
                                  method: :delete,
                                  data: { confirm: 'Are you sure to cancel the request?'} %>
                  </td>
                  <% end %>
                </table>
              </tr>
              <% end %>
              <% end %>
              <% end %>
              </div>
            </div>
          </div>
        </div>
        <div class="panel panel-default">
          <div class="panel-heading">
            <h4 class="panel-title">
              <a class="accordion-toggle collapsed" data-toggle="collapse" data-parent="#accordion" href="#collapse2">Accepted</a>
            </h4>
          </div>
          <div id="collapse2" class="panel-collapse collapse">
            <div class="panel-body">
            <div style="overflow-x:auto;">
              <% @items.each do |item| %>
              <% if !(item.borrow_requests.nil?) %>
              <% item.borrow_requests.each do |borrow_request| %>
                
              <table>
                <% if borrow_request.approval && borrow_request.return_status !=2 %>
                <tr>
                  <td>
                    <%= borrow_request.item.item_name %>
                  </td>
                  <td>
                    <%= getCategoryName(borrow_request.item.category_id) %>
                  </td>
                  <td>
                    Borrower: 
                    <%= link_to borrow_request.user_profile.username, user_profile_path(borrow_request.user_profile.id)%>
                  </td>
                  <td>
                    <%= borrow_request.borrow_date%> to <%=borrow_request.return_date%>
                  </td>
                  <td>
                    <%= link_to 'Show Request', item_borrow_request_path(:item_id=>borrow_request.item.id, :id=>borrow_request.id) %> |</td>
                  <td>
                    <%= link_to 'Show Item', user_profile_item_path(:user_profile_id=>current_user.id, :id=>borrow_request.item.id) %> | </td>
                  <td>
                    <%= link_to 'Remove', item_borrow_request_path(:item_id=>borrow_request.item.id, :id=>borrow_request.id),
                                  method: :delete,
                                  data: { confirm: 'Are you sure to cancel the request?'} %>
                  </td>
                </tr>
                <% end %>
              </table>
              
              <% end %>
              <% end %>
              <% end %>
              </div>
            </div>
          </div>
        </div>
      <div class="panel panel-default">
        <div class="panel-heading">
          <h4 class="panel-title">
            <a class="accordion-toggle collapsed" data-toggle="collapse" data-parent="#accordion" href="#collapse3">Rejected</a>
          </h4>
        </div>
        <div id="collapse3" class="panel-collapse collapse">
          <div class="panel-body">
          <div style="overflow-x:auto;">
            <% @items.each do |item| %>
            <% if !(item.borrow_requests.nil?) %>
            <% item.borrow_requests.each do |borrow_request| %>
            <table>
              <% if borrow_request.approval == false %>
              <tr>
                <td>
                  <%= borrow_request.item.item_name %>
                </td>
                <td>
                  <%= getCategoryName(borrow_request.item.category_id) %>
                </td>
                <td>
                  Borrower: 
                  <%= link_to borrow_request.user_profile.username, user_profile_path(borrow_request.user_profile.id)%>
                </td>
                <td>
                  <%= borrow_request.borrow_date%> to <%=borrow_request.return_date%>
                </td>

                <td>
                  <%= link_to 'Show Request', item_borrow_request_path(:item_id=>borrow_request.item.id, :id=>borrow_request.id) %> |</td>
                <td>
                  <%= link_to 'Show Item', user_profile_item_path(:user_profile_id=>current_user.id, :id=>borrow_request.item.id) %> | </td>

                <td>
                  <%= link_to 'Remove', item_borrow_request_path(:item_id=>borrow_request.item.id, :id=>borrow_request.id),
                                method: :delete,
                                data: { confirm: 'Are you sure to cancel the request?'} %>
                </td>
              </tr>
              <% end %>
            </table>
            
            <% end %>
            <% end %>
            <% end %>
            </div>
          </div>
        </div>
      </div>
      <div class="panel panel-default">
      <div class="panel-heading">
        <h4 class="panel-title">
          <a class="accordion-toggle collapsed" data-toggle="collapse" data-parent="#accordion" href="#collapse4">History</a>
        </h4>
      </div>
      <div id="collapse4" class="panel-collapse collapse">
        <div class="panel-body">
        <div style="overflow-x:auto;">
          <% @items.each do |item| %>
          <% if !(item.borrow_requests.nil?) %>
          <% item.borrow_requests.each do |borrow_request| %>
            
          <table>
            <% if borrow_request.return_status == 2 %>
            <tr>
              <td>
                <%= borrow_request.item.item_name %>
              </td>
              <td>
                <%= getCategoryName(borrow_request.item.category_id) %>
              </td>
              <td>
                Borrower: 
                <%= link_to borrow_request.user_profile.username, user_profile_path(borrow_request.user_profile.id)%>
              </td>
              <td>
                <%= borrow_request.borrow_date%> to <%=borrow_request.return_date%>
              </td>
              <td>
                <%= link_to 'Show Request', item_borrow_request_path(:item_id=>borrow_request.item.id, :id=>borrow_request.id) %> |</td>
              <td>
                <%= link_to 'Show Item', user_profile_item_path(:user_profile_id=>current_user.id, :id=>borrow_request.item.id) %> | </td>

              <td>
                <%= link_to 'Remove', item_borrow_request_path(:item_id=>borrow_request.item.id, :id=>borrow_request.id),
                              method: :delete,
                              data: { confirm: 'Are you sure to cancel the request?'} %>
              </td>
            </tr>
            <% end %>
          </table>
          <% end %>
          <% end %>
          <% end %>
          </div>
        </div>
      </div>
    </div>

      </div>
    </div>
  </row>
</div>

app/views/user_profiles/new.html.erb
<%= render 'profile_form' %>

<%= link_to 'Cancel', "/welcome" %>