config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  # For test for Gmap
#  resources :gmap
  
  # ROOT
  root "welcome#index"

  # Home page
  get "welcome", to: "welcome#index"

  get "welcome/sitemap"
  get "welcome/about"
  get "welcome/contact_us"
  get "welcome/terms_of_service"
  get "welcome/privacy_policy"
  get "welcome/faq"

  # Pages
  get "borrow_from_others", to: "user_profiles#borrow_from_others"

  # Resources
  resources :items
  resources :user_profiles, :path => "account/profiles"
  resources :categories

  get "lend_to_others", to: "user_profiles#lend_to_others"
  get "lend_rating", to: "user_profiles#lend_rating"
  get "borrow_rating", to: "user_profiles#borrow_rating"
  get "comment_history", to: "user_profiles#comment_history"
  resources :user_profiles do
    resources :items
  end

  resources :items do
    collection { post :search, to: "items#index" }
  end

  #resources :borrow_requests

  resources :items do
    resources :borrow_requests
  end
  
  resources :items do
    resources :comments
  end

  #  devise_for :users, skip: [:sessions]
  #  devise_scope :user do
  #    get 'signin', to: 'devise/sessions#new', as: :new_user_session
  #    post 'signin', to: 'devise/sessions#create', as: :user_session
  #    delete 'signout', to: 'devise/sessions#destroy', as: :destroy_user_session
  #  end

  devise_for :users,
    :path => "account",
    :path_names => {
      :sign_in => "login",
      :sign_out => "logout",
      :password => "secret",
      :confirmation => "verification",
      :unlock => "unblock",
    }, skip: [:registration]
  devise_scope :user do
    get "/account/cancel", to: "devise/registrations#cancel", as: :cancel_user_registration
    get "/account/sign_up", to: "devise/registrations#new", as: :new_user_registration
    get "/account/edit", to: "devise/registrations#edit", as: :edit_user_registration
    post "/account", to: "devise/registrations#create", as: :user_registration
  end
end

app/models/item.rb
class Item < ApplicationRecord
  # relations
  belongs_to :user_profile
  belongs_to :category
  has_many :borrow_requests, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_one_attached :image

  # validations
  validates :description, length: {maximum: 200}
  validates :item_name, presence: true,
                        length: {maximum: 50}
  validate :correct_image_type
  #no quantity right now
  #validates :quantity, numericality: {only_integer: true, greater_than: 0}

  # actions
  before_create :set_default_image
  #after_create :set_left_quantity

  private

  #def set_left_quantity
  #  self.left_quantity = self.quantity
  #end

  def correct_image_type
      if self.image.attached? && !self.image.content_type.start_with?('image/')
        self.errors.add(:self, 'Must be an image')
      end
    end

  def set_default_image
    if !self.image.attached?
      self.image.attach(io: File.open(Rails.root.join("app", "assets", "images", "default_item.jpg")), filename: "default_item.jpg", content_type: "image/jpg")
    end
  end
end

app/controllers/items_controller.rb
# todo: add current user as the
class ItemsController < ApplicationController
  respond_to :json, :js, :html

  def index
    @unlogin = params[:user_profile_id].nil?
    @notsearching = params[:q].nil?
    @search = Item.ransack(params[:q])

    if !@notsearching
      @search_items = @search.result(distinct: true)
      @search_words = params[:q][:item_name_or_description_cont]
    elsif !@unlogin
      @user_profile = UserProfile.find(params[:user_profile_id])
      @search_items = @user_profile.items
      @search_words = ""
    else
      @search_items = Item.all
      @search_words = ""
    end
    
    puts @search_items

    @markers = load_markers(@search_items)
    @current_latlon = {:lat => current_user.user_profile.latitude, :lng => current_user.user_profile.longitude}
  end

  def show
    @unlogin = params[:user_profile_id].nil?

    @item = Item.find(params[:id])
    #  @borrow_request = @item.borrow_request
    @borrow_requests = @item.borrow_requests
    @owner = UserProfile.find(@item.user_profile.id)
  end

  def create
    @user_profile = UserProfile.find(params[:user_profile_id])
    @item = @user_profile.items.create(item_params)

    if @item.save
      redirect_to user_profile_items_path(@user_profile)
      flash[:notice] = "Item created."
    else
      @s = ""
      for m in @item.errors.full_messages
        @s = @s + m + ".   "
      end
      flash[:alert] = @s
      render "new"
    end
  end

  def new
    @user_profile = UserProfile.find(params[:user_profile_id])
    @item = Item.new
  end

  def edit
    @user_profile = UserProfile.find(params[:user_profile_id])
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    @user_profile = @item.user_profile
    if @item.update(item_params)
      redirect_to user_profile_item_path(:user_profile_id => @user_profile.id)
      flash[:notice] = "Item updated."
    else
      @s = ""
      for m in @item.errors.full_messages
        @s = @s + m + ".   "
      end
      flash[:alert] = @s
      render "edit"
    end
  end

  def destroy
    @item = Item.find(params[:id])
    @item.destroy

    redirect_to user_profile_items_path
  end

  def load_markers(search_items)
    
    @item_infos = Hash.new
    search_items.each do |item|
      @profile = item.user_profile
      latlon = {:lat => @profile.latitude, :lon => @profile.longitude}
      
      if !@item_infos[latlon].nil?
        @item_infos[latlon].push(item)
      else
        @item_infos[latlon] = [item]
      end
    end
    
    @infos_array = []
    @item_infos.each do |latlon, items|
      @infos_array.push({:latlon => latlon, :items => items})
    end
    
    @load_markers = 
    Gmaps4rails.build_markers(@infos_array) do |info, marker|
      @items = info[:items]
      @latlon = info[:latlon]

      marker.lat @latlon[:lat]
      marker.lng @latlon[:lon]

      marker.infowindow render_to_string(:partial => "/items/infowindow_template", :locals => {:items => @items})
    end
  end

  private

  def item_params
    params.require(:item).permit(:item_name, :category_id, :quantity, :status,
                                 :search_text, :image, :description)
  end
end

app/helpers/items_helper.rb
module ItemsHelper
  def itemAvaiableMessage(x)
    x ? "This item is currently available" : "This item is currently unavailable"
  end

  def getCategoryName(id)
    @category = Category.find(id)
    @category.category_name
  end
end

app/views/items/_form.html.erb
<%= form_with(model: [@user_profile, @user_profile.items.build], local: true, class: "form-group") do |form| %>
  <div class="form-group">
    <%= form.label :item_name, "Item Name"%><br>
    <%= form.text_field :item_name, :class => 'form-text text-muted form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :description, "Item Description"%><br>
    <%= form.text_area :description, :class => 'form-text text-muted form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :category_id, "Categories"%><br>
    <%= form.collection_select :category_id, Category.order(:category_name), :id, :category_name,
    include_blank: true, :class => 'form-control' %>
  </div>

  <!--no quantity right now
  <div class="form-group">
  <p>
    <%= form.label :quantity, "Quantity" %><br>
    <%= form.number_field :quantity, :class => 'form-control'%>
  </p>
  </div>
  -->

  <div class="form-group">
    <%= form.label :image, "Item Image" %>
    <%= form.file_field :image, direct_upload: true, accept:"image/png,image/jpg,image/jpeg"  %>
  </div>

  <div class="form-group">
    <%= form.label :status, "Item is currently available" %>
    <%= form.check_box :status, {checked: true}, :class => 'form-control' %>
  </div>

  <p>
    <%= form.submit "Create", class: "btn btn-primary" %>
  </p>

<% end %>

app/views/items/_infowindow_template.html.erb
<html>
<head>
<style>
table {
    border-collapse: collapse;
    width: 100%;
}

th, td {
    padding: 6px;
    text-align: left;
    border-bottom: 1px solid #ddd;
}
</style>
</head>
<body>

<table>
  <% @items.each do |item| %>
  <tr>
    <td>
      <dl>
        <dt><strong><%= link_to item.item_name, item_path(item.id) %></strong></dt>
        <% if item.status == true%>
          <dd>- Status: Available</dd>
        <% else %>
          <dd>- Status: Currently unavailable</dd>
        <% end %>
        <dd>- Category: <%= getCategoryName(item.category_id) %></dd>
      </dl>
    </td>
  </tr>
  <% end %>
</table>

</body>
</html>

app/views/items/_item_search_box.html.erb
<div class="search_field-custom" id="search-box">
  <%= search_form_for @search, html: {class: ""} do |f| %>
  <div class="row search-row">
    <div class="search-text">
      <%= f.search_field :item_name_or_description_cont, class: "form-control", placeholder: "Search Items" %>
    </div><br />
    <div class="search-submit">
      <%= f.submit "Search", class: "btn btn-light" %>
    </div>
  </div>
  <% end %>

  <span id="advanced-search-span">
    <div>
      <button class="btn-sm btn-outline-warning advanced-search-button" type="button" data-toggle="collapse" data-target="#advanced-search">
        Advanced Search
      </button>
    </div>

    <div id="advanced-search" class="collapse navbar-form navbar-left">
      <%= search_form_for @search do |f| %>
      <ul class="navbar-left list-inline">
        <li class="list-inline-item">
          <%=f.label :item_name_cont, 'Item Name'%>
          <%=f.text_field :item_name_cont%>
        </li>

        <li class="list-inline-item">
          <%=f.label :description_cont, 'Item Description'%>
          <%=f.text_field :description_cont, class:"text"%>
        </li>

        <li class="list-inline-item">
          <%=f.label :status, 'Available'%>
          <%=f.check_box :status_eq%>
        </li>
      </ul>
      <%= f.submit "Search", class: "radius button"%>
      <% end %>
    </div>
  </span>
</div>

<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

app/views/items/edit.html.erb
<div class='row'>
  <div class='col-2'>
  </div>
  <div class="col-8">
    <div class="text-form form-group">

      <%= form_with(model: @item, local: true, class: "form-group") do |form| %>
        <div class="form-group">
          <%= form.label :item_name, "Item Name"%><br>
          <%= form.text_field :item_name, :class => 'form-text text-muted form-control' %>
        </div>

        <div class="form-group">
          <%= form.label :description, "Item Description"%><br>
          <%= form.text_area :description, :class => 'form-text text-muted form-control' %>
        </div>

        <div class="form-group">
          <%= form.label :category_id, "Categories"%><br>
          <%= form.collection_select :category_id, Category.order(:category_name), :id, :category_name,
          include_blank: true, :class => 'form-control' %>
        </div>

        <div class="form-group">
          <%= form.label :image, "Item Image" %>
          <%= form.file_field :image, direct_upload: true, accept:"image/png,image/jpg,image/jpeg" %>
        </div>

        <div class="form-group">
          <%= form.label :status, "Item is currently available" %>
          <%= form.check_box :status, {checked: true}, :class => 'form-control' %>
        </div>

        <p>
          <%= form.submit "Create", class: "btn btn-primary" %>
        </p>

      <% end %>

    </div>
  </div>
</div>

app/views/items/index.html.erb
<!-- refer to the repository for code --
  -- This is the google script needed for the map-->

<script src="//maps.google.com/maps/api/js?key=AIzaSyDUoCq1U8tO8sZZEseqfOnxXffU6idiIPg"></script>
<script src="//cdn.rawgit.com/mahnunchik/markerclustererplus/master/dist/markerclusterer.min.js"></script>
<script src='//cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/infobox/src/infobox_packed.js' type='text/javascript'></script>
<script src='//underscorejs.org/underscore.js' type='text/javascript'></script>


<div class="container">
  <div class="row">
    <div class='col-1'>
    </div>
    <div class='col-8'>
      <ul class="nav">
        <% unless @search_items.empty? %>
        <li class="nav-item">
          <%= sort_link(@search, :item_name, 'Sort by Item Name', class:"nav-link") %>
        </li>
        <li class="nav-item">
          <%= sort_link(@search, :category_id, 'Sort by Category', class:"nav-link") %>
        </li>
        <%end%>
      </ul>
    </div>
    <% if @unlogin && !@search_items.empty? %>
    <div class='col-2'>
      <!-- Button trigger modal -->
      <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#myModal">
        View On Map
      </button>
    </div>
    <%end%>
  </div>

  <div class="row">
    <div class='col-1'>
    </div>
    <div class='col-8'>
      <div class="container">
        <div class="tab-content" id="pills-tabContent">
          <div class="tab-pane show active" id="item-list">
            <% @search_items.each do |item| %>
            <tr>
              <div class="Portfolio">
                <%= link_to item_path(item) do %>
                <%= image_tag item.image.variant(resize: "180x180!"), class:"index-image" %>
                <div class="desc">
                  <ul>
                    <li>
                      <%=item.item_name%>
                    </li>
                    <li>
                      <%=getCategoryName(item.category_id)%>
                    </li>
                    <li>
                      <% if item.status == true %>
                        <span class="glyphicon glyphicon-ok" aria-hidden="true"></span>
                      <% else %>
                        <span class="glyphicon glyphicon-remove" aria-hidden="true"></span>
                      <% end %>
                    </li>
                  </ul>
                </div>
                <% end %>
              </div>
              <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>

  <!--% if @search_items.empty? && @search_words!='' %-->
  <% if @unlogin && @search_items.empty? && !@search_words.nil? %>
  <a href="https://www.amazon.ca/s/field-keywords=<%=@search_words%>"> Try to look for <strong>
      <%=@search_words%></strong> on Amazon</a>
  <br>
  <% end %>
  <hr noshade>
</div>


<!------------- Start of the map ------------->
<script>
  var items = <%=raw @markers.to_json %>
  var latlon = <%=raw @current_latlon.to_json %>
</script>
<head>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.6/css/bootstrap.min.css">
</head>

<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      </div>
      <div class="modal-body">
        <div class="row">
          <div class="col-md-12 modal_body_map">
            <div class="location-map" id="location-map">
              <div style="width: 700px; height: 450px;" id="map_canvas"></div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<!------------- End of the map ------------->
<!-- Placed at the end of the document so the pages load faster -->
<script src="//ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.6/js/bootstrap.min.js"></script>

app/views/items/new.html.erb
<div class='row'>
  <div class='col-2'>
  </div>
  <div class="col-8">
    <div class="text-form form-group">
      <h1>New Item</h1>
      <%= render 'form' %>
      <%= link_to 'Back', user_profile_items_path %>
    </div>
  </div>
</div>

app/views/items/show.html.erb
<div class="row">
  <div class="col-1">
  </div>
  <div class="col-10 item-top">
    <div class="item-go-back">
      <%= link_to :back do %>
      <%= fa_icon 'arrow-left', class:"go-back-fa"%>
      <%= content_tag :span, "Back", class:"go-back-link"%>
      <% end %>
    </div>
    <div class="category-tag">
      <strong>
        <%= link_to(getCategoryName(@item.category_id), search_items_path(q: {category_id_eq: @item.category_id}), :method =>:post) %> > </strong>
    </div>
    <% if current_user.id == @owner.id %>
    <div class="owner-action">
      <% if !(@borrow_requests.nil?)%>
      <%= link_to 'RequestList', item_borrow_requests_path(:item_id =>@item.id), class: "btn btn-info"%>
      <% end %>
      <%= link_to 'Edit', edit_user_profile_item_path(current_user.id), class: "btn btn-info" %>
      <%= link_to 'Remove', user_profile_item_path(current_user.id, :id=>@item.id),
                  method: :delete,
    	      data: { confirm: 'Are you sure?'}, class: "btn btn-info" %>
    </div>
    <% end %>
  </div>
</div>
<div class="item-showcase">
  <!-- <div class="item-showcase-pattern"> -->
  <div class="container">
    <div class="row">
      <div class="item-background">
        <div class="row">
          <div class="item-image">
            <%= image_tag @item.image.variant(gravity: 'center') %>

            <%- if !@item.borrow_requests.empty? && current_user.id != @owner.id%>
                <div class="panel panel-default">
                  <div class="panel-heading">
                    <h4 class="panel-title">
                        <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion" href="#collapseOne">Not Avaiable Time</a>
                    </h4>
                  </div>
                  <div id="collapseOne" class="panel-collapse collapse">
                    <div class="panel-body">
                    <div style="overflow-x:auto;">
                    <table>
                    <tr>
                      <td><strong>From</strong></td>
                      <td>| <strong>To</strong></td>
                    </tr>
                    <% @item.borrow_requests.each do |current_req|%>
                      <% if !current_req.approval.nil?%>
                      <% if current_req.approval && current_req.return_status!=2%>
                      <tr>
                        <td><%= current_req.borrow_date %></td>
                        <td>| <%= current_req.return_date %></td>
                      </tr>
                      <% end %>
                      <% end %>
                    <% end %>
                    </table>
                    </div>
                    </div>
                  </div>
                </div>

            <% end %>
          </div>
          <div class="item-detail">
            <h1>
              <%= @item.item_name %>
            </h1>
            <div class="item-description">
              <p>Owner:
                <%= link_to @item.user_profile.username, user_profile_path(@item.user_profile.id), class:"owner-link" %>
              </p>
              <p>
                <%= @item.description %>
              </p>
              <p>
                <% if @item.status == true %>
                  <span class="glyphicon glyphicon-ok" aria-hidden="true"></span>
                <% else %>
                  <span class="glyphicon glyphicon-remove" aria-hidden="true"></span>
                <% end %>
                <%= itemAvaiableMessage(@item.status) %>
              </p>
              <% if @item.status == true%>
                <p>
                  <% if current_user.id != @owner.id %>
                  <%= render 'borrow_requests/request_form' %>
                  <% end %>
                </p>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
<!-- comment area -->

<div class="row">
  <div class="col-1">
  </div>
  <div class="col-10">
<% if !@item.comments.empty?%>
  <div class="panel panel-default comment-pannel">
    <div class="panel-heading">
      <h4 class="panel-title">
         <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion" href="#collapseTWO">Comment:</a>
      </h4>
    </div>
    <div id="collapseTWO" class="panel-collapse collapse">
      <div class="panel-body">
      <div style="overflow-x:auto;">
      <table>

        <% @item.comments.each do |current_req|%>
        <tr>
          <td><%=link_to current_req.user_profile.username, user_profile_path(current_req.user_profile_id)%></td>
          <td><%= current_req.comment_message%>
          | <%=current_req.comment_date %></td>
          <% if(current_req.user_profile_id==current_user.id)%>
            <td><%=link_to "Edit", edit_item_comment_path(current_req.item_id,current_req.id),
            data: { confirm: 'Are you sure?'}, class: "btn btn-info" %></td>
            <td><%=link_to "Delete", item_comment_path(current_req.item_id,current_req.id),
            method: :delete,
            data: { confirm: 'Are you sure?'}, class: "btn btn-info" %></td>
          <%end%>
        </tr>
        <% end %>
    </table>
    </div>
    </div>
  </div>
</div>
<%end%>
</div>
</div>