config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  # For test for Gmap
#  resources :gmap
  
  # ROOT
  root "welcome#index"

  # Home page
  get "welcome", to: "welcome#index"

  get "welcome/sitemap"
  get "welcome/about"
  get "welcome/contact_us"
  get "welcome/terms_of_service"
  get "welcome/privacy_policy"
  get "welcome/faq"

  # Pages
  get "borrow_from_others", to: "user_profiles#borrow_from_others"

  # Resources
  resources :items
  resources :user_profiles, :path => "account/profiles"
  resources :categories

  get "lend_to_others", to: "user_profiles#lend_to_others"
  get "lend_rating", to: "user_profiles#lend_rating"
  get "borrow_rating", to: "user_profiles#borrow_rating"
  get "comment_history", to: "user_profiles#comment_history"
  resources :user_profiles do
    resources :items
  end

  resources :items do
    collection { post :search, to: "items#index" }
  end

  #resources :borrow_requests

  resources :items do
    resources :borrow_requests
  end
  
  resources :items do
    resources :comments
  end

  #  devise_for :users, skip: [:sessions]
  #  devise_scope :user do
  #    get 'signin', to: 'devise/sessions#new', as: :new_user_session
  #    post 'signin', to: 'devise/sessions#create', as: :user_session
  #    delete 'signout', to: 'devise/sessions#destroy', as: :destroy_user_session
  #  end

  devise_for :users,
    :path => "account",
    :path_names => {
      :sign_in => "login",
      :sign_out => "logout",
      :password => "secret",
      :confirmation => "verification",
      :unlock => "unblock",
    }, skip: [:registration]
  devise_scope :user do
    get "/account/cancel", to: "devise/registrations#cancel", as: :cancel_user_registration
    get "/account/sign_up", to: "devise/registrations#new", as: :new_user_registration
    get "/account/edit", to: "devise/registrations#edit", as: :edit_user_registration
    post "/account", to: "devise/registrations#create", as: :user_registration
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :store_user_location!, if: :storable_location?
  before_action :set_search
  before_action :authenticate_user!
  before_action :new_message
  before_action :item_status_check
  before_action :getUserName

  def getUserName
    if !current_user.nil?
      @current_user_profile = UserProfile.find(current_user.id)
      @current_user_name = @current_user_profile.username
    end
  end

  def item_status_check
    #check and update status for all the items..
    if !current_user.nil?
      @comment_user = UserProfile.find(current_user.id)
    end
    @all_items = Item.all
    @all_items.each do |status_item|
      @item_ava = true
      status_item.borrow_requests.each do |request|
        if request.approval == true
          #check if any accepted items lend out today
          if (((request.borrow_date >= Date.today) && (request.return_status != 2)) || (request.return_status == 3) || (request.return_status == 4))
            @item_ava = false
          end
        end
      end
      status_item.update_attribute(:status, @item_ava)
    end
  end

  # checking if there are new message
  def new_message
    @new_message = false
    @message_num = 0
    @new_requests = Array.new
    if !current_user.nil?
      @current_user_profile = UserProfile.find(current_user.id)
      @user_name = @current_user_profile.username
      # checking if there are importance request message?
      @current_user_profile.items.each do |it|
        it.borrow_requests.each do |req|
          if !req.read_status
            @new_message = true
            @message_num = @message_num + 1
            @new_requests << req.id
            #flash[:notice] = "You have new requset"
          elsif req.return_status == 0 && req.borrow_date <= Date.today && req.approval
            @new_message = true
            @message_num = @message_num + 1
            @new_requests << req.id
            #flash[:notice] = "have items need to be deliverd today"
          elsif req.return_status == 1
            @new_message = true
            @message_num = @message_num + 1
            @new_requests << req.id
            #flash[:notice] = "You item returned"
          end
        end
      end
      @current_user_profile.borrow_requests.each do |req|
        if ((req.approval && req.return_status == 3) || (!req.borrower_read_status))
          @new_message = true
          @message_num = @message_num + 1
          @new_requests << req.id
          #flash[:notice] = "deliverd check received?"
        elsif req.return_status == 4 && req.return_date <= Date.today
          @new_message = true
          @message_num = @message_num + 1
          @new_requests << req.id
          #flash[:notice] = "Return!!!"
        end
      end
    end
  end

  def after_sign_in_path_for(resource)
    if current_user.sign_in_count == 1
      edit_user_profile_path(User.find(current_user.id).user_profile.id)
    else
      stored_location_for(resource) || root_path
    end
  end

  def after_sign_out_path_for(resource)
    root_path
  end

  private

  def set_search
    @search = Item.ransack(params[:q])
  end

  def storable_location?
    request.get? && is_navigational_format? && !devise_controller? && !request.xhr?
  end

  def store_user_location!
    store_location_for(:user, request.fullpath)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def bootstrap_class_for flash_type
    { success: "alert-success", error: "alert-danger", alert: "alert-warning", notice: "alert-info" }[flash_type.to_sym] || flash_type.to_s
end

  def flash_messages(opts = {})
    flash.each do |msg_type, message|
      concat(content_tag(:div, message, class: "alert #{bootstrap_class_for(msg_type)} sticky", id:"flash-messages") do
        concat content_tag(:button, "x", class: "close", data: {dismiss: "alert"})
        concat message
      end)
    end
    nil
  end
end

app/views/application/_footer.html.erb
<footer class="page-footer">
  <div class="footer-top">
    <div class="container">
      <div class="row">
        <div class="col-md-4 col-lg-4 footer-about wow fadeInUp">
          <p>
            Borrow from your friends and the world around you.
          </p>
          <h3>Contact</h3>
          <p><i><%=fa_icon "map-marker", class:"footer-icon"%></i>&nbsp&nbsp&nbsp&nbsp27 King's College Cir, Toronto, ON M5S 3H7</p>
          <p><i><%=fa_icon "phone", class:"footer-icon"%></i>&nbsp&nbspPhone: (416) 978-2011</p>
          <p><i><%=fa_icon "envelope", class:"footer-icon"%></i>&nbspEmail: <a href="mailto:hamster@nest.com">hamster@nest.com</a></p>
        </div>
        <div class="col-md-4 col-lg-4 offset-lg-1">

        </div>
        <div class="col-md-4 col-lg-3 footer-social wow fadeInDown">
          <h3>Follow us</h3>
          <p>
            <!-- link to twitter -->
            <p><a href="https://twitter.com/HamsterNest?ref_src=twsrc%5Etfw" class="twitter-follow-button" data-show-count="false">Follow @HamsterNest</a>
              <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
            </p>

            <!-- link to facebook -->
            <p>
              <%=link_to href="https://www.facebook.com/hamsternest.page", target: "_blank" do %>
              <%= image_tag ("facebook_icon.png"), class: "social-icon"%>
              <% end %>
              HamsterNest Page
            </p>

            <!-- link to instagram -->
            <p>
              <%=link_to href="https://www.instagram.com/hamsternestofficial", target: "_blank" do %>
              <%= image_tag ("instagram_icon.png"), class: "social-icon"%>
              <% end %>
              Hamsternestofficial
            </p>

        </div>
      </div>
    </div>
  </div>
  <div class="footer-bottom">
    <div class="container">
      <div class="row">
        <div class="col-md-5 footer-copyright">
          <p>&copy; HamsterNest 2018-2019</p>
        </div>
        <div class="col-md-7 footer-menu">
          <nav class="navbar navbar-light navbar-expand-md">
            <div class="collapse navbar-collapse" id="navbarNav">
              <ul class="navbar-nav ml-auto">
                <li class="nav-item nav-item-footer">
                  <a class="nav-link scroll-link" href="#top-content">Top</a>
                </li>
                <li class="nav-item nav-item-footer">
                  <a><%= link_to "    Sitemap    ", "/welcome/sitemap", class:"nav-link scroll-link" %></a>
                </li>
                <li class="nav-item nav-item-footer">
                  <a><%= link_to "    About us    ", "/welcome/about", class:"nav-link scroll-link" %></a>
                </li>
                <li class="nav-item nav-item-footer">
                  <a><%= link_to "Terms of Service", "/welcome/terms_of_service", class:"nav-link scroll-link" %></a>
                </li>
                <li class="nav-item nav-item-footer">
                  <a><%= link_to " Privacy Policy ", "/welcome/privacy_policy", class:"nav-link scroll-link" %></a>
                </li>
                <li class="nav-item nav-item-footer">
                  <a><%= link_to "     FAQ       ", "/welcome/faq", class:"nav-link scroll-link" %></a>
                </li>
              </ul>
            </div>
          </nav>
        </div>
      </div>
    </div>
  </div>
</footer>

app/views/application/_top_banner.erb
<!-- Navigation -->
<nav class="navbar navbar-expand-lg navbar-dark navbar-custom">

  <div class="navbar-brand-custom">
    <%- if registerInProgress %>
    <div class="float-left navbar-brand-text-only" href="#">Hamster Nest</div>
    <%- else %>
    <%= link_to root_path do %>
    <div id="hamster-nest" class="float-left navbar-brand-text">Hamster Nest</div>
    <% end %>
    <% end %>
  </div>

  <%- if user_signed_in? && !registerInProgress %>
  <%= render "items/item_search_box" %>
  <% else %>
  <div class="container" id="search-box">
  </div>
  <% end %>

  <button id="navi-hide" class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="float-right" id="navbarResponsive">
    <ul class="navbar-nav">
      <%- if registerInProgress %>
      <!-- this is the first time the user log in -->
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav">
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              My Account
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
              <%= link_to "Add profile", edit_user_profile_path(current_user.id),:class => "dropdown-item" %>
              <% if !current_user.nil? %>
              <% if !@comment_user.comments.empty? %>
              <%= link_to "Comment History", comment_history_path(current_user.id),:class => "dropdown-item" %>
              <% end %>
              <% end %>
              <%= link_to "Log Out", destroy_user_session_path, method: :delete, :class => "dropdown-item" %>
            </div>
          </li>
        </ul>
      </div>
      <%- elsif !user_signed_in? %>
      <!-- this is when the user is not signed in -->
      <li class="nav-item">
          <%= link_to 'Register', new_user_registration_path, :id => "register", :class => "btn btn-link" %><br>
      </li>
      <li class="nav-item">
        <%= link_to 'Sign In', new_user_session_path, :class => "btn btn-light" %><br>
      </li>
      <%- else %>
      <!-- this is when the user is already signed in -->
      <% if @new_message %>
        <li class="nav-item dropdown">
        <span class="notify-badge"><%=@message_num%></span>
        <a href="#" class="nav-link noti-link dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Item Updates</a>
        <ul class="dropdown-menu notify-drop">
          <div class="drop-content">

          <% @new_requests.each do |req_id|%>
          <li>
            <% @new_req = BorrowRequest.find(req_id)%>
            <% if @new_req.user_profile.id!= current_user.id%>
            <%= link_to @new_req.item.item_name, item_borrow_request_path(:item_id=>@new_req.item.id, :id=>req_id, :read_status=>true), :method=> :put, :class => "dropdown-item"  %>
            <%else%>
            <%= link_to @new_req.item.item_name, item_borrow_request_path(:item_id=>@new_req.item.id, :id=>req_id, :borrower_read_status=>true), :method=> :put, :class => "dropdown-item"  %>
            <%end%>
            </li>
          <%end%>
          </div>
          </ul>
      <%end%>

      <li class="nav-item dropdown">
        <%= link_to 'New item', new_user_profile_item_path(current_user.id), class: "btn btn-info"  %>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          My Lists
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
        <% if !current_user.nil? %>
        <% if !@comment_user.items.empty? %>
          <%= link_to "My items", user_profile_items_path(:user_profile_id =>current_user.user_profile_id), :class => "dropdown-item" %>
          <% end %>
          <% end %>        
          <%= link_to "Borrow list", borrow_from_others_path(), :class => "dropdown-item" %>
          <%= link_to "Lend list", lend_to_others_path, :class => "dropdown-item"  %>
        </div>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <%=@current_user_name%>
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
          <%= link_to "View my profile", user_profile_path(current_user.user_profile_id), :class => "dropdown-item" %>
          <% if !current_user.nil? %>
          <% if !@comment_user.comments.empty? %>
          <%= link_to "Comment History", comment_history_path(current_user.id),:class => "dropdown-item" %>
          <% end %>
          <% end %>
          <%= link_to "Log Out", destroy_user_session_path, method: :delete, :class => "dropdown-item" %>
        </div>
      </li>
      <% end %>
    </ul>
  </div>

</nav>

app/views/application/about.html.erb
<h1>About HamsterNest</h1>
<%= link_to 'Home page', "/welcome" %>